### ISSUE TITLE
text formatting/encoding issue turning = signs to =3D

### ISSUE THREAD

**Issue by spacewaffle** [icy/google-group-crawler#17]
I got a number of warnings during my scrape that spat out these messages. I could be wrong but it looks like '=' signs are getting acii values inserted into the strings.

WARNING: Could not parse (and so ignoring) '<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt;tex='
WARNING: Could not parse (and so ignoring) '<b>Register for our November 29 internship event at</b> <a href=3D"http://w='
WARNING: Could not parse (and so ignoring) '<p class=3D"MsoNormal" style=3D"margin-bottom:0in;margin-bottom:.0001pt;tex='

**Comment by icy** [comment]
@spacewaffle Would you mind sharing your group name (in case it's public)? If not, I'd like to know more logs and details (e.g, at which step do you get this warning).

Thanks

**Comment by spacewaffle** [comment]
Unfortunately the group isn't public, but I'm trying to import groups data into discourse. here's some more logging.

^C/Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/utilities.rb:239:in `to_crlf': Interrupt
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/message.rb:1998:in `raw_source='
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/message.rb:2121:in `init_with_string'
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/message.rb:129:in `initialize'
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
	from /Users/Jon/.rvm/gems/ruby-2.0.0-p648/gems/mail-2.6.4/lib/mail/mail.rb:188:in `read_from_string'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:86:in `block in all_messages'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:68:in `each'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:68:in `each_with_index'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:68:in `all_messages'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:190:in `create_email_indices'
	from /Users/Jon/sites/discourse/script/import_scripts/mbox.rb:23:in `execute'
	from googlegroups.rb:49:in `execute'
	from /Users/Jon/sites/discourse/script/import_scripts/base.rb:45:in `perform'
	from googlegroups.rb:92:in `<main>''

This is part of a project migrating google groups to Discourse. I'm following the instructions here:
https://meta.discourse.org/t/migration-of-google-groups-to-discourse/48012

**Comment by icy** [comment]
I'm not author of the `mbox.rb`. Where do you get that script? There is probably a problem with encoding processing in this script.

**Comment by spacewaffle** [comment]
I added the link to the script in the bottom of my previous post, but it's here for you to look at. Your scraper is a dependency so I figured maybe it's to do with the scraper and not the script.
https://meta.discourse.org/t/migration-of-google-groups-to-discourse/48012

link to repo:
https://github.com/pacharanero/discourse/blob/master/script/import_scripts/mbox.rb

**Comment by icy** [comment]
Thank you @spacewaffle . How about using encoding instruction?

Current version
```
require 'sqlite3'
require File.expand_path(File.dirname(__FILE__) + "/base.rb")
```

New version / instruction

```
#!/usr/bin/env ruby
# encoding: utf-8

require 'sqlite3'
require File.expand_path(File.dirname(__FILE__) + "/base.rb")
```

**Comment by spacewaffle** [comment]
I believe I fixed this issue by upgrading our ruby version to 2.3 which does utf-8 by default

**Comment by icy** [comment]
Great to hear that. Thanks for your feedback.
