### ISSUE TITLE
Can not get all the mbox

### ISSUE THREAD

**Issue by demostars** [icy/google-group-crawler#21]
Thank you for your work.

I try to get a google group named fanfou-digest which has 1373 topics but with this crawler there are 21 files in mbox folder,  the newest 21 topics, is this a bug or did i do something wrong? Can i get 1373 files with this crawler?

**Comment by icy** [comment]
Hi @demostars,

Is it this public group https://groups.google.com/forum/#!forum/fanfou-digest ? I will give a try if something wrong happens.

**Comment by demostars** [comment]
Yes it is a publiuc group and accounding to the file in threads folder, it stoped when there is another page to  continue,
![1510736561 1](https://user-images.githubusercontent.com/20697190/32827383-f736a764-ca26-11e7-835e-30d28b12be5b.png)

alse i try to run crawler with cookie，same question, is there any other group has the same question? doesn't it come with pages?

**Comment by icy** [comment]
@demostars The script can work with paging: as long as it sees something like `_escaped_fragment_` in the output it will try to follow that link. In case it doesn't work, maybe there is an encoding issue. 

I haven't tested the script on any encoding other than `UTF-8`. Maybe you force the script to use that

```
$ LANG=en_US.UTF-8 ./crawer.sh -sh
```

This will not hurt any contents as I understand. My testing script is still running with your group I will let you know if I have the same issue.

**Comment by demostars** [comment]
Well, that make sense, i am running Ubuntu with Chinese, but still does not work, i will try to run the crawler  on another Ubuntu with English. 

Thank you!

**Comment by icy** [comment]
@demostars On an Ubuntu system with US locales, I can see the script works well (so far).  The generated script is here https://gist.github.com/icy/6f8683ded1ce0860dad387f8d845aa64 . You may use them to download all _(almost)_ original mbox files.

Hope this helps.

**Comment by demostars** [comment]
Thank you, i tryed to run On an Ubuntu system with US locales, the same issue, so strange. 

Thank you so much!

**Comment by icy** [comment]
weird. maybe you have any problem with your network? Maybe you send me the output for further debugging? Or you can try the script above that's the complete list of all messages that you need to download from the current archive.

**Comment by demostars** [comment]
Yep, with your script above i have downloaded all the archive, what output do you need? In the terminal or in the folder?

**Comment by icy** [comment]
@demostars How is thing going? Are you able to use the script?

I have added some tests and the result is found on Travis-CI, for example https://travis-ci.org/icy/google-group-crawler/jobs/348543280

**Comment by demostars** [comment]
Thanks,that works on me. 

I think you can close this issues.
