### ISSUE TITLE
400 Bad Request Error

### ISSUE THREAD

**Issue by bisherbas** [icy/google-group-crawler#22]
For some reason the `wget` link is not formatted properly so when I run the update.sh or wget.sh, I get the following error. I replaced the actual group name with GROUPNAME for privacy.

**update.sh content** https://gist.githubusercontent.com/bisherbas/c46129e17fb60bfa7df08ebd70458bf4/raw/1b98f4cb41688c1c73cc4a8dcae64cdd6a80f24e/gistfile1.txt

**example of terminal output**
`--2017-12-01 14:41:09--  https://groups.google.com/forum/message/raw?msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/VIhjJiLXvD8/HGdTkrMDCAAJ
Resolving groups.google.com (groups.google.com)... 108.177.112.139, 108.177.112.138, 108.177.112.102, ...
Connecting to groups.google.com (groups.google.com)|108.177.112.139|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2017-12-01 14:41:09 ERROR 400: Bad Request.`

**Comment by bisherbas** [comment]
`   1 #!/usr/bin/env bash
   2
   3 export _ORG="${_ORG:-}"
   4 export _GROUP="${_GROUP:-GROUPNAME}"
   5 export _D_OUTPUT="${_D_OUTPUT:-./GROUPNAME/}"
   6 export _USER_AGENT="${_USER_AGENT:-Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0}"
   7 export _WGET_OPTIONS="${_WGET_OPTIONS:---load-cookies /home/james/cookies.txt
   8                       --keep-session-cookies}"
   9
  10 __wget_hook ()
  11 {
  12     :
  13 }
  14 __wget__ ()
  15 {
  16     if [[ ! -f "$1" ]]; then
  17         wget --user-agent="$_USER_AGENT" $_WGET_OPTIONS "$2" -O "$1";
  18         __wget_hook "$1" "$2";
  19     fi
  20 }
  21 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.-19n3Nyk3LQ.KuGLugtqAAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/-19n3Nyk3LQ/KuGLugtqAAAJ"
  22 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.-19n3Nyk3LQ.LS-weaH9AAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/-19n3Nyk3LQ/LS-weaH9AAAJ"
  23 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.-19n3Nyk3LQ.RTwtMUjWAAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/-19n3Nyk3LQ/RTwtMUjWAAAJ"
  24 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.-19n3Nyk3LQ.TD_uttXUAAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/-19n3Nyk3LQ/TD_uttXUAAAJ"
  25 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.-19n3Nyk3LQ.XHn9pdFoAAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/-19n3Nyk3LQ/XHn9pdFoAAAJ"
  26 __wget__ "./GROUPNAME//mbox/m.https:..groups.google.com.d.msg.GROUPNAME.4S2zCDxoj48.45T1nZX6CAAJ" "https://groups.google.com/forum/message/raw?                 msg=GROUPNAME/https://groups.google.com/d/msg/GROUPNAME/4S2zCDxoj48/45T1nZX6CAAJ"`

**Comment by bisherbas** [comment]
Same for me. Getting nothing but 400 bad requests.

**Comment by bisherbas** [comment]
Closing. Works now. Future visitors: Make sure the group name set in the code is all **lowercase**.

**Comment by icy** [comment]
Thanks a lot @bisherbas . I have had a small commit to make sure `_GROUP` is in lowercase.

**Comment by bisherbas** [comment]
Thanks a lot!
