### ISSUE TITLE
Problem on Bash / Windows

### ISSUE THREAD

**Issue by icy** [icy/google-group-crawler#26]
See also https://stackoverflow.com/questions/50749033/0-byte-file-extracted-when-downloading-google-group-data

**Comment by nevesnunes** [comment]
It's not clear what subsystem OP is using, but it works for me under MSYS2. My packages are:

```
msys/msys2-runtime 2.11.1-2
msys/bash 4.4.019-3
msys/coreutils 8.30-1
msys/wget 1.19.5-1
msys/sed 4.5-1
msys/gawk 4.2.1-1
```

**Comment by icy** [comment]
@nevesnunes I think it's the Linux system provided in Windows 10 (and higher). I haven't had any Windows (>=) 10  to test here though.

**Comment by t-np** [comment]
@nevesnunes works for me under my wsl environment with GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu) i used the debian base when installing wsl
