### ISSUE TITLE
Crawler doesn't work when tags are enabled on the group

### ISSUE THREAD

**Issue by LeeKevin** [icy/google-group-crawler#27]
When tags or categories are enabled on the group, the crawler simply returns a list of the tags/categories.

To properly access a list of all topics when tags or categories are enabled for a group, the topics URL is: `https://groups.google.com/{ORG}/forum/?_escaped_fragment_=categories/{GROUP}`

Just FYI!

**Comment by icy** [comment]
I didn't know that feature, @LeeKevin . Thank you very much I will fix the script soon.

**Comment by LeeKevin** [comment]
To get it to work, I've just updated the initial `_download_page` call from `?_escaped_fragment_=forum/$_GROUP`to `?_escaped_fragment_=categories/$_GROUP`. 

This will work in both cases--regardless of whether the group has categories or tags enabled.
